<?xml version="1.0" encoding="utf-8"?><Database Name="PersonaDB" Class="dbEntityDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=PersonaDB;Integrated Security=True" SettingsObjectName="Negocio.Properties.Settings" SettingsPropertyName="PersonaDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.persona" Member="personas">
    <Type Name="persona">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
    </Type>
  </Table>
</Database>