//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameWorkCRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presidentes
    {
        public int PRE_codigo { get; set; }
        public string PRE_nombre { get; set; }
        public string PRE_apellidos { get; set; }
        public string PRE_partido { get; set; }
    }
}
