//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public int i_IdPersona { get; set; }
        public string v_NombresApellidos { get; set; }
        public string v_DNI { get; set; }
        public string v_Direccion { get; set; }
        public Nullable<System.DateTime> t_FechaNacimiento { get; set; }
        public string v_Telefono { get; set; }
    }
}
